version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: container_engine
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  container-engine:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/container_engine
      REDIS_URL: redis://redis:6379
      PORT: 3000
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      JWT_EXPIRES_IN: 3600
      API_KEY_PREFIX: ce_api_
      KUBERNETES_NAMESPACE: container-engine
      DOMAIN_SUFFIX: container-engine.app
      RUST_LOG: container_engine=debug,tower_http=debug
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
      - target_cache:/app/target
    working_dir: /app

volumes:
  postgres_data:
  redis_data:
  target_cache: